import type { Product } from "@/lib/types"

export const products: Product[] = [
  {
    id: 1,
    name: "Vitamin C 1000mg",
    description: "High-potency vitamin C supplement for immune support.",
    price: 12.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Vitamins & Supplements",
    rating: 4.5,
    reviewCount: 128,
    inStock: true,
    discount: 0,
  },
  {
    id: 2,
    name: "Digital Thermometer",
    description: "Accurate digital thermometer for temperature measurement.",
    price: 9.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Medical Devices",
    rating: 4.2,
    reviewCount: 75,
    inStock: true,
    discount: 10,
  },
  {
    id: 3,
    name: "Pain Relief Tablets",
    description: "Fast-acting pain relief for headaches and minor aches.",
    price: 7.49,
    image: "/placeholder.svg?height=300&width=300",
    category: "Medications",
    rating: 4.7,
    reviewCount: 203,
    inStock: true,
    discount: 0,
  },
  {
    id: 4,
    name: "First Aid Kit",
    description: "Comprehensive first aid kit for home and travel.",
    price: 24.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "First Aid",
    rating: 4.8,
    reviewCount: 156,
    inStock: true,
    discount: 15,
  },
  {
    id: 5,
    name: "Multivitamin Tablets",
    description: "Daily multivitamin supplement for overall health.",
    price: 15.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Vitamins & Supplements",
    rating: 4.4,
    reviewCount: 89,
    inStock: true,
    discount: 0,
  },
  {
    id: 6,
    name: "Hand Sanitizer",
    description: "Alcohol-based hand sanitizer for effective germ protection.",
    price: 3.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Personal Care",
    rating: 4.3,
    reviewCount: 112,
    inStock: true,
    discount: 0,
  },
  {
    id: 7,
    name: "Blood Pressure Monitor",
    description: "Digital blood pressure monitor for home use.",
    price: 49.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Medical Devices",
    rating: 4.6,
    reviewCount: 67,
    inStock: true,
    discount: 20,
  },
  {
    id: 8,
    name: "Allergy Relief Spray",
    description: "Fast-acting nasal spray for allergy symptom relief.",
    price: 11.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Medications",
    rating: 4.1,
    reviewCount: 43,
    inStock: true,
    discount: 0,
  },
]

// Add the missing getProducts function
export function getProducts(): Promise<Product[]> {
  // In a real application, this would fetch from an API
  // For now, we'll just return the static products array
  return Promise.resolve(products)
}
